### ISSUE TITLE
Gather User Requirements

### ISSUE THREAD

**Issue by Jingyong14** [drshahizan/software-engineering#15]
Collect data from interviews and analyze

**Comment by wei2030** [comment]
Question:

1. What are the primary goals of implementing a student feedback system?

- it is needed for student to give feedback to each lecturer that taught them in that current semester.
- this student feedback system was started since the new courses was introduced
- this system enhanced the quality of teaching system and the teaching environment

2. What challenges or barriers do you anticipate in implementing this system, and how do you plan to overcome them?

- this system need to consider 3 category which is for diploma students, undergraduate students and also the postgraduate students.
- this system will be normally open at the 10th week of every semester for student to access and give feedback
- the challenges or barriers that always faced are the users cannot access to this system
- this is due to the large amount of user login at the same time at has caused congestion of the system
- the previous version of student feedback system used my UTM cannot directly access when the user is not in the range of UTM and they need to use VPN to access this system
- VPN can be a large problem for the user to use it

3. How do you currently manage and analyze student feedback data?

- student feedback data is a data that are confidential
- only the faculty administrator and the lecturer can access to the existing data
- this is help to protect the privacy of feedback data and can't be access by the outsider
- CDex staff currently work on managing the system and ensure it always work when it is needed
- they had introduce myAIMs system which allow the user directly access to the system using myAIMs application although they are not in UTM

4. Are there any legal or ethical considerations that need to be taken into account when implementing this system, such as data privacy or confidentiality concerns?

- yes, all the feedback data need to keep it securely to prevent the outsider easily access to this system and get the data

5. How will the success of this feedback system be measured, and what are your expectations for its impact?

- all lecturer need to know what to do with this system
- if they get the rating lower than average rating, that lecturer will been given guidance on their teaching method
- they will been called to have a training during the semester break

6. How would you like to analyze and visualize the feedback data, and what metrics do you think are important to track?

- data is not interpret by the CDex staff
- the existing data will only sent to each faculty for the purpose analysis to occur
- the CDex staff only done with processing data and no any analysis occur at this stage
- in the analysis stage by each faculty, they can know how much and requirement of lecturer need training
- training process is carry out by CTLD department in UTM

7. What are the key pain points or challenges currently faced in collecting and managing student feedback?

- each faculty will be responsible to determine which subject to been assessed
- the period for them to determine which subject to been assessed is between week 6 to week 8 of each semester
- during this period they can simply modified and take off every subject to be assessed
- after the given period, it still can be modified but a more complex process need to conducted

8. How would you like the system to handle anonymous feedback submissions? Should there be an option for students to provide feedback anonymously?

- Yes, it is important for student to provide feedback anonymously
- this allow them provide the most accurate feedback without worrying their data been expose to others or the lecturer
- so the faculty could know each student study environment and determine the needed to make a change on that method

**Comment by wei2030** [comment]
Question:

1. What are your expectations from the feedback system? 

- this system should be able to provide feedback to selected lecturer
- this system should also give opinion or suggestion to the lecturer on their teaching method and environment so the lecturer can improve their teaching ways and figure out alternative ways to increase the effectiveness of teaching

2. What features or functionalities do you think are the most important to have in this system?

- current system is quite general, which means they have a standard rubric to carry out an evaluation of each lecturer
- the propose system should have option for student to choose the ways they would like to perform their evaluation and feedback on the current semester
- There should have different rubric for evaluation of tutorial mode or lecture mode

3. How often would you like to provide feedback throughout the semester?

- end of the semester is the best time for student to provide feedback in this system

4. Have you used the ePPP feedback systems in the past? What did you like or dislike about them?

- Yes, I dislike the previous system
- the questions asked in the previous system were too general and not specific for the current subject to be evaluate
- student might not take it seriously to fill up the feedback form
- the form is boring and keep asking the same question for all lecturer
- the question in the form should be specific by each lecturer, so that can get the feedback that they expected to get

5. How do you think the feedback system could help you improve your academic performance and experience?

- At the end of the semester the current student that take that course will provide feedback to the lecturer
- However, they might not take back the same subject during the coming semester
- So, the gathered feedbacks are used to improved the teaching method of the lecturer on the next semester

6. Would you prefer anonymous feedback or do you prefer to know who provided the feedback?

- I would like to prefer anonymous feedback
- because if a student give a bad feedback, this may affect the pointer and their score in exam
- We had heard some lecturer from others university give their student who give a bad evaluation a bad result

7. How user-friendly do you find the current feedback system, and what improvements would you suggest?

- current system is simple to us and allow the student provide comment in text box only
- so, for the proposed system should include a modern UI
- it should improve the accessibility to this system and avoid the congestion when lots of user login in one time
- the previous system also have a poor responsive toward font size, the word cannot be enlarge and this had caused some student cannot see the question clearly
- the font size should follow the screen size which is flexible to change
